import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const createReagents = await prisma.inventoryOfReagents.createMany({
    data: [
        {
            casNumber: "75-07-0",
            chemicalName: "Acetaldehyde",
            manufacturerName: "Acetaldehyde",
            unit: "mL",
            quantity: 350,
            DGClass: "3",
            PG: "1",
            hazSub: true,
        },
        {
            casNumber: "64-19-7",
            chemicalName: "Acetic Acid",
            manufacturerName: "Acetic Acid",
            description: "glacial",
            unit: "mL",
            quantity: 920,
            DGClass: "8",
            PG: "2",
            hazSub: true,
        },
        {
            casNumber: "67-64-1",
            chemicalName: "Acetone",
            manufacturerName: "Acetone",
            unit: "mL",
            quantity: 4800,
            DGClass: "8",
            PG: "2",
            riskPhrase: "11, 36, 66, 67",
            safetyPhrase: "9, 16, 25, 26, 29, 33",
            hazSub: true,
        },
        {
            casNumber: "98-86-2",
            chemicalName: "Acetophenone, extra pure",
            manufacturerName: "Acetophenone, extra pure",
            unit: "mL",
            quantity: 900,
            DGClass: "nil",
            subRisk: "nil",
            PG: "nil",
            hazSub: true,
        },
        {
            casNumber: "1336-21-6",
            chemicalName: "Amonia Solution",
            manufacturerName: "Amonia Solution",
            description: "28%",
            unit: "mL",
            quantity: 1800,
            DGClass: "8",
            PG: "3",
            riskPhrase: "34, 50",
            safetyPhrase: "7, 26, 45, 23, 24/25, 36/37/38, 41",
            hazSub: true,
        },
        {
            casNumber: "98-86-2",
            chemicalName: "n-Amyl Alcohol",
            manufacturerName: "Pentanol",
            unit: "mL",
            quantity: 1000,
            DGClass: "3",
            PG: "3",
        },
    ],
});

console.log(`Created Reagents: ${JSON.stringify(createReagents)}`);
