services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: RAILS
        ports:
            - "${PORT:-3000}:${PORT:-3000}"
        environment:
            - NODE_ENV=production
            - PORT=${PORT:-3000}
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_ENABLED=${AUTH_ENABLED}
            - ORIGIN=${ORIGIN}
            - NEXTAUTH_URL=${ORIGIN}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - DATABASE_URL=${DATABASE_URL}
            - DB_HOST=${DB_HOST}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - DB_DATABASE=${DB_DATABASE}
        restart: unless-stopped
