version: "3"

services:
  app:
    # Build the app image from the Dockerfile
    build: .
    # Name the app container as rails
    container_name: rails
    # Map the port 3000 of the container to the port 3000 of the host
    ports:
      - "3000:3000"
    # Link the app container to the db container
    depends_on:
      - db
  
  db:
    # Use the db image from the Dockerfile
    image: db
    # Name the db container as mysql-db
    container_name: mysql-db
    # Map the port 3306 of the container to the port 3306 of the host
    ports:
      - "3306:3306"
