import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const createReagents = await prisma.inventoryOfReagents.createMany({
    data: [
        {
            itemNumber: "1a",
            casNumber: "75-07-0",
            chemicalName: "Acetaldehyde",
            manufacturerName: "Acetaldehyde",
            unit: "mL",
            maxQuantity: 50,
            currentQuantity: 50,
            DGClass: "3",
            PG: "1",
            hazSub: true,
        },
        {
            itemNumber: "1b",
            casNumber: "75-07-0",
            chemicalName: "Acetaldehyde",
            manufacturerName: "Acetaldehyde",
            unit: "mL",
            maxQuantity: 300,
            currentQuantity: 300,
            DGClass: "3",
            PG: "1",
            hazSub: true,
        },
        {
            itemNumber: "2a",
            casNumber: "64-19-7",
            chemicalName: "Acetic Acid",
            manufacturerName: "Acetic Acid",
            description: "glacial",
            unit: "mL",
            maxQuantity: 20,
            currentQuantity: 20,
            DGClass: "8",
            PG: "2",
            hazSub: true,
        },
        {
            itemNumber: "2b",
            casNumber: "64-19-7",
            chemicalName: "Acetic Acid",
            manufacturerName: "Acetic Acid",
            description: "food grade",
            unit: "mL",
            maxQuantity: 900,
            currentQuantity: 900,
            DGClass: "8",
            PG: "2",
            riskPhrase: "11, 36, 66, 67",
            safetyPhrase: "9, 16, 25, 26, 29, 33",
            hazSub: true,
        },
        {
            itemNumber: "3a",
            casNumber: "67-64-1",
            chemicalName: "Acetone",
            manufacturerName: "Acetone",
            unit: "mL",
            maxQuantity: 800,
            currentQuantity: 800,
            DGClass: "8",
            PG: "2",
            riskPhrase: "11, 36, 66, 67",
            safetyPhrase: "9, 16, 25, 26, 29, 33",
            hazSub: true,
        },
        {
            itemNumber: "3b",
            casNumber: "67-64-1",
            chemicalName: "Acetone",
            manufacturerName: "Acetone",
            unit: "mL",
            maxQuantity: 1000,
            currentQuantity: 1000,
            DGClass: "8",
            PG: "2",
            riskPhrase: "11, 36, 66, 67",
            safetyPhrase: "9, 16, 25, 26, 29, 33",
            hazSub: true,
        },
        {
            itemNumber: "3c",
            casNumber: "67-64-1",
            chemicalName: "Acetone",
            manufacturerName: "Acetone",
            unit: "mL",
            maxQuantity: 1000,
            currentQuantity: 1000,
            DGClass: "8",
            PG: "2",
            riskPhrase: "11, 36, 66, 67",
            safetyPhrase: "9, 16, 25, 26, 29, 33",
            hazSub: true,
        },
        {
            itemNumber: "3d",
            casNumber: "67-64-1",
            chemicalName: "Acetone",
            manufacturerName: "Acetone",
            unit: "mL",
            maxQuantity: 2000,
            currentQuantity: 2000,
            DGClass: "8",
            PG: "2",
            riskPhrase: "11, 36, 66, 67",
            safetyPhrase: "9, 16, 25, 26, 29, 33",
            hazSub: true,
        },
        {
            itemNumber: "4",
            casNumber: "98-86-2",
            chemicalName: "Acetophenone, extra pure",
            manufacturerName: "Acetophenone, extra pure",
            unit: "mL",
            maxQuantity: 900,
            currentQuantity: 900,
            DGClass: "nil",
            subRisk: "nil",
            PG: "nil",
            hazSub: true,
        },
        {
            itemNumber: "5",
            casNumber: "1336-21-6",
            chemicalName: "Amonia Solution",
            manufacturerName: "Amonia Solution",
            description: "28%",
            unit: "mL",
            maxQuantity: 1800,
            currentQuantity: 1800,
            DGClass: "8",
            PG: "3",
            riskPhrase: "34, 50",
            safetyPhrase: "7, 26, 45, 23, 24/25, 36/37/38, 41",
            hazSub: true,
        },
        {
            itemNumber: "6",
            casNumber: "98-86-2",
            chemicalName: "n-Amyl Alcohol",
            manufacturerName: "Pentanol",
            unit: "mL",
            maxQuantity: 1000,
            currentQuantity: 1000,
            DGClass: "3",
            PG: "3",
        },
    ],
});

console.log(`Created Reagents: ${JSON.stringify(createReagents)}`);
