import backup from "@vorlefan/prisma-backup";
import dayjs from "dayjs";
import prisma from "../prisma.js";

const { runBackup } = backup;

const [
    SchoolYear,
    Users,
    Admins,
    Teachers,
    Students,
    ChangeRoleRequests,
    Notifications,
    GradeSection,
    Units,
    Laboratories,
    LaboratoryLocations,
    LaboratoryReservations,
    InventoryOfMaterials,
    InventoryOfEquipment,
    InventoryOfReagents,
    EquipmentRequests,
    MaterialRequests,
    ReagentRequests,
    LaboratoryRequests,
] = await prisma.$transaction([
    prisma.schoolYear.findMany({}),
    prisma.users.findMany({}),
    prisma.admins.findMany({}),
    prisma.teachers.findMany({}),
    prisma.students.findMany({}),
    prisma.changeRoleRequests.findMany({}),
    prisma.notifications.findMany({}),
    prisma.gradeSection.findMany({}),
    prisma.units.findMany({}),
    prisma.laboratories.findMany({}),
    prisma.laboratoryLocations.findMany({}),
    prisma.laboratoryReservations.findMany({}),
    prisma.inventoryOfMaterials.findMany({}),
    prisma.inventoryOfEquipment.findMany({}),
    prisma.inventoryOfReagents.findMany({}),
    prisma.equipmentRequests.findMany({}),
    prisma.materialRequests.findMany({}),
    prisma.reagentRequests.findMany({}),
    prisma.laboratoryRequests.findMany({}),
]);

await runBackup({
    models: {
        SchoolYear,
        Users,
        Admins,
        Teachers,
        Students,
        ChangeRoleRequests,
        Notifications,
        GradeSection,
        Units,
        Laboratories,
        LaboratoryLocations,
        LaboratoryReservations,
        InventoryOfMaterials,
        InventoryOfEquipment,
        InventoryOfReagents,
        EquipmentRequests,
        MaterialRequests,
        ReagentRequests,
        LaboratoryRequests,
    },
    backupFolderName: String(dayjs().format("MMM-DD-YYYY-HH;mm;ss")),
});
